-- هذا الكود تنفيذه في Supabase Dashboard
-- اذهب إلى: SQL Editor > New Query > الصق هذا الكود > Run

-- جدول المنتجات
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  stock INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- تفعيل Row Level Security للسلامة
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- السماح بالتعديل للمصادق عليهم فقط
CREATE POLICY "Authenticated users can manage products" ON products
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- منح إذن الإدراج للمصادق عليهم
GRANT ALL ON products TO authenticated;
GRANT ALL ON products TO anon;
GRANT ALL ON products TO service_role;

-- إدراج بيانات تجريبية
INSERT INTO products (name, category, price, stock) VALUES
  ('لابتوب Dell XPS 15', 'أجهزة كمبيوتر', 4500, 45),
  ('شاشة LG 27"', 'شاشات', 1200, 32),
  ('كيبورد Logitech', 'ملحقات', 150, 120),
  ('ماوس Logitech MX', 'ملحقات', 200, 85),
  ('طابعة HP LaserJet', 'طابعات', 800, 18),
  ('سماعة Sony WH-1000XM4', 'سماعات', 600, 50);